-- Table to store chains (was created externally)
CREATE TABLE IF NOT EXISTS chains
(
    chain_id   bigint              NOT NULL
        CONSTRAINT chains_new_pkey
            PRIMARY KEY,
    name       varchar(32)         NOT NULL,
    beefy_name char(32) DEFAULT '' NOT NULL,
    enabled    boolean  DEFAULT TRUE
);

-- Table to store buyback transactions (was created externally)
CREATE TABLE IF NOT EXISTS bifi_buyback
(
    id            integer GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    block_number  integer                  NOT NULL,
    txn_timestamp timestamp with time zone NOT NULL,
    event_idx     smallint,
    txn_hash      char(66)                 NOT NULL,
    bifi_amount   numeric(26, 18)          NOT NULL,
    bifi_price    numeric(26, 18)          NOT NULL,
    buyback_total numeric(26, 18) GENERATED ALWAYS AS ((bifi_amount * bifi_price)) STORED
);

CREATE UNIQUE INDEX IF NOT EXISTS bifi_buyback_idx_txn_timestamp_event_idx
    ON bifi_buyback (txn_timestamp DESC, event_idx ASC) INCLUDE (txn_timestamp);

-- Table to store harvest transactions (was created externally)
CREATE TABLE IF NOT EXISTS harvests
(
    chain_id           bigint
        CONSTRAINT fk_chains_new
            REFERENCES chains
            ON UPDATE CASCADE,
    block_number       integer,
    txn_idx            smallint,
    event_idx          smallint,
    txn_timestamp      timestamp with time zone,
    txn_hash           char(66),
    vault_id           varchar(64),
    call_fee           numeric(30, 18),
    gas_fee            numeric(30, 18),
    platform_fee       numeric(24, 18),
    strategist_fee     numeric(24, 18),
    harvest_amount     numeric(36, 18),
    native_price       numeric(26, 18),
    want_price         numeric(40, 18),
    is_cowllector      boolean DEFAULT FALSE,
    strategist_address char(42),
    CONSTRAINT harvests_pk
        UNIQUE (chain_id, block_number, txn_idx, event_idx)
);

CREATE INDEX IF NOT EXISTS harvests_chain_id_txn_timestamp_index
    ON harvests (chain_id, (timezone('UTC'::text, txn_timestamp)::date));

CREATE INDEX IF NOT EXISTS idx_harvests_chain_ts_block
    ON harvests (chain_id ASC, txn_timestamp DESC, block_number ASC) INCLUDE (txn_timestamp);

-- Table to store feebatch harvest transactions (was created externally)
CREATE TABLE IF NOT EXISTS feebatch_harvests
(
    chain_id       bigint                   NOT NULL,
    block_number   integer                  NOT NULL,
    txn_timestamp  timestamp with time zone NOT NULL,
    txn_hash       character(66)            NOT NULL,
    harvest_usd    numeric(26, 18),
    treasury_amt   numeric(26, 18),
    rewardpool_amt numeric(26, 18),
    native_price   numeric(26, 18),
    stable_price   numeric(20, 18),
    CONSTRAINT feebatch_harvests_unique
        UNIQUE (chain_id, block_number)
);

CREATE INDEX IF NOT EXISTS feebatch_harvests_date_idx
    ON feebatch_harvests (chain_id, (timezone('UTC'::text, txn_timestamp)::date));

COMMENT ON COLUMN feebatch_harvests.harvest_usd IS 'Total USD Value of all Harvested Tokens';
COMMENT ON COLUMN feebatch_harvests.treasury_amt IS 'Stable Tokens Sent to Treasury';
COMMENT ON COLUMN feebatch_harvests.rewardpool_amt IS 'Native Tokens Sent to BIFI Reward Pool';
